### ISSUE TITLE
`npm link`ed sub-modules don't transpile

### ISSUE THREAD

**Issue by dcrockwell** [FreeAllMedia/stimpak#17]
```
Error: Couldn't find preset "es2015" relative to directory "/Users/dcrockwell/Dropbox/Code/stimpak-project-basic-information"
    at /Users/dcrockwell/.nvm/versions/node/v5.11.1/lib/node_modules/stimpak/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/dcrockwell/.nvm/versions/node/v5.11.1/lib/node_modules/stimpak/node_modules/babel-core/lib/transformation/file/options/option-manager.js:387:20)
    at OptionManager.mergePresets (/Users/dcrockwell/.nvm/versions/node/v5.11.1/lib/node_modules/stimpak/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:10)
    at OptionManager.mergeOptions (/Users/dcrockwell/.nvm/versions/node/v5.11.1/lib/node_modules/stimpak/node_modules/babel-core/lib/transformation/file/options/option-manager.js:330:14)
    at OptionManager.addConfig (/Users/dcrockwell/.nvm/versions/node/v5.11.1/lib/node_modules/stimpak/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/Users/dcrockwell/.nvm/versions/node/v5.11.1/lib/node_modules/stimpak/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/Users/dcrockwell/.nvm/versions/node/v5.11.1/lib/node_modules/stimpak/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at compile (/Users/dcrockwell/.nvm/versions/node/v5.11.1/lib/node_modules/stimpak/node_modules/babel-register/lib/node.js:112:69)
    at loader (/Users/dcrockwell/.nvm/versions/node/v5.11.1/lib/node_modules/stimpak/node_modules/babel-register/lib/node.js:158:14)
Wompus:stimpak-project dcrockwell$ stimpak project
/Users/dcrockwell/.nvm/versions/node/v5.11.1/lib/node_modules/stimpak/es5/lib/cli/stimpak.cli.js:57
```

**Comment by dcrockwell** [comment]
This happens when you npm link an unpublished sub-generator.
